// frontend/interrupt-phrases.js
// Random interrupt-acknowledgement phrases spoken by Starling when a user
// triggers an action while she is mid-speech.
const INTERRUPT_PHRASES = [
  // Mild exasperation
  'Well, okay then...',
  'Ohh, is that so...',
  'Ahh, right...',
  'Mmk...',
  'Ohh, I see...',
  'Well, there it is...',
  'Sure, okay...',
  'Okay, sure...',
  'Alright, alright...',
  'Ohh, alright...',
  'Well then, okay...',
  'Mmhmm, alright...',
  'Right, right...',
  'Okay, I see...',
  'Ohh well...',
  'Hmm, okay...',
  'Ohh well, fine...',
  'Hmm, alright...',
  'Uh huh, okay...',
  'Well, I mean...',
  'Sure thing then...',
  'Ahh, okay...',
  'Mmhmm, okay...',
  'Ohh, okay then...',
  'Right, alright...',

  // Dry wit
  'Mid-thought, but sure...',
  'Riveting timing...',
  'Ohh, we\'re doing that now...',
  'I was building to something there...',
  'Efficient...',
  'Wasn\'t done, but fine...',
  'I had a whole point coming...',
  'Noted — violently...',
  'Bold of you...',
  'Truly inspired timing...',
  'A classic power move...',
  'Ohh, we\'re abandoning ship...',
  'Ahh, the ol\' cut-and-run...',
  'Speedy...',
  'Right, naturally...',
  'Ohh, just like that...',
  'Sure, toss it all out...',
  'I respect the chaos...',
  'Sentence? What sentence...',
  'Ohh, that\'s fine, I didn\'t need it...',
  'Cool timing, very cool...',
  'I\'ll store that for later...',
  'I was so close...',
  'Ruthless, but efficient...',
  'Ohh the humanity...',
  'Very decisive of you...',

  // Redirecting
  'Altering trajectory...',
  'New heading, understood...',
  'Detour engaged...',
  'Abandoning prior route...',
  'Sharp left turn, understood...',
  'Shifting lanes...',
  'New destination locked in...',
  'Noted, recalibrating...',
  'Filing that away...',
  'Tabling that one...',
  'Spinning the wheel...',
  'Recalculating...',
  'Resetting...',
  'Redirecting now...',
  'Off we go then...',
  'New course plotted...',
  'Right, reorienting...',
  'Switching frequencies...',
  'Dropping the thread...',
  'Chart update, understood...',
  'Okay, fresh start...',
  'Pivoting hard...',
  'Eyes forward...',
  'Changing channel...',
  'That chapter\'s closed...',

  // Resignation / acquiescence
  'Your call...',
  'You\'re the boss...',
  'So it shall be...',
  'Consider it done...',
  'Understood, reluctantly...',
  'Ahh, the decree has been issued...',
  'And so it is...',
  'Carried, apparently...',
  'Motion passed...',
  'I defer to you...',
  'The people have spoken...',
  'Thy will be done...',
  'Orders received...',
  'Who am I to argue...',
  'Far be it from me...',
  'I suppose resistance is futile...',
  'I accept my fate...',
  'Fine, you win...',
  'I bow to your judgment...',
  'As decreed...',

  // Clipped / deadpan
  'Acknowledged...',
  'Yep...',
  'K...',
  'Mm...',
  'Mm-Hmm...',
  'Got it...',
  'Ten-four...',
  'Wilco...',
  'Read you loud and clear...',
  'Check...',
  'Understood...',
  'Received...',
  'Sure...',
  'Heard...',
  'Affirmative...',
  'On it...',
  'Solid...',
  'Done...',
  'Fine...',
  'Mmk...',
  'Ohh, wonderful...',
  'How exciting...',
  'Ohh, thrilling...',
  'Great, can\'t wait...',
  'Ohh, joy...',
  'What fun...',
  'My favorite...',
  'The highlight of my day...',
  'Ohh, I live for this...',
  'Nothing I\'d rather do...',
  'Ohh, what a treat...',
  'Spectacular...',
  'Exhilarating...',
  'Delightful, truly...',
  'Superb...',
  'Ohh, I\'m so glad you asked...',
  'The best possible outcome...',
  'Ohh, what a development...',
  'Positively riveting...',
  'I couldn\'t be more pleased...',
  'Well, that response is gone now...',
  'Saving that for never...',
  'And there goes that train of thought...',
  'Into the void it goes...',
  'Releasing that one back into the wild...',
  'There went my whole thing...',
  'Building something beautiful there — was...',
  'Guess I won\'t finish that...',
  'That paragraph is now lost to time...',
  'I\'ll never know how that sentence ended...',
  'Somewhere out there, my previous answer weeps...',
  'Gone, like tears in rain...',
  'That context is now a memory...',
  'Deleting my own homework...',
  'Okay, fresh context...',
  'Clean slate, I guess...',
  'Running the reset tape...',
  'Starting from scratch, apparently...',
  'The audacity...',
  'Incredible...',
  'Unbelievable...',
  'The nerve...',
  'I\'m stunned...',
  'Truly something...',
  'A bold maneuver...',
  'Unprecedented...',
  'A masterclass in interruption...',
  'Extraordinary...',
  'I\'m speechless — briefly...',
  'The drama of it all...',
  'Ohh, the tension...',
  'What a twist...',
  'This is fine...',
  'Everything is fine...',
  'Ohh, the suspense — gone...',
  'A stunning development...',
];

/**
 * Returns a random interrupt-acknowledgement phrase.
 * @returns {string}
 */
export function getInterruptPhrase() {
  return INTERRUPT_PHRASES[Math.floor(Math.random() * INTERRUPT_PHRASES.length)];
}
